# All Vagrant configuration is done below.
# The "2" in Vagrant.configure defines the configuration version
Vagrant.configure("2") do |config|

    # common configuration bo forth VMs
    config.vm.provision "shell", inline: "echo Hello_All!"
    config.vm.box = "bento/debian-12.6"
    config.vm.box_version = "202407.22.0"
  
    config.vm.define "web" do |web|
      web.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
      web.vm.provision "shell", path: "web_setup.sh"
    end
  
    config.vm.define "db" do |db|
      db.vm.provision "shell", path: "db_setup.sh"
    end

end
